version: "2"
services:

  prod:
    restart: always
    build: .
    hostname: "{{.Service.Name}}-{{.Task.Slot}}"
    command: yarn serve
    volumes:
      - /usr/local/smart-signature/ss-backend-config/config.prod.js:/usr/src/app/config/config.default.js
      - /usr/local/smart-signature/ss-backend-config/apiaccesstoken.js:/usr/src/app/config/apiaccesstoken.js
      - /usr/local/smart-signature/ss-backend-config/wechat_config.js:/usr/src/app/config/wechat_config.js
    ports:
      - 7653:7001
    networks:
      overlay:
  
  prod2:
    restart: always
    build: .
    hostname: "{{.Service.Name}}-{{.Task.Slot}}"
    command: yarn serve
    volumes:
      - /usr/local/smart-signature/ss-backend-config/config.prod.js:/usr/src/app/config/config.default.js
      - /usr/local/smart-signature/ss-backend-config/apiaccesstoken.js:/usr/src/app/config/apiaccesstoken.js
      - /usr/local/smart-signature/ss-backend-config/wechat_config.js:/usr/src/app/config/wechat_config.js
    ports:
      - 7654:7001
    networks:
      overlay:

  test:
    restart: always
    build: .
    hostname: "{{.Service.Name}}-{{.Task.Slot}}"
    command: yarn dev
    volumes:
      - /usr/local/smart-signature/ss-backend-config/config.local.js:/usr/src/app/config/config.default.js
      - /usr/local/smart-signature/ss-backend-config/apiaccesstoken.js:/usr/src/app/config/apiaccesstoken.js
      - /usr/local/smart-signature/ss-backend-config/wechat_config.js:/usr/src/app/config/wechat_config.js
    ports:
      - 7652:7001
    networks:
      overlay:

  local:
    restart: always
    build: .
    hostname: "{{.Service.Name}}-{{.Task.Slot}}"
    command: yarn dev
    volumes:
      - /usr/local/smart-signature/ss-backend-config/config.local.js:/usr/src/app/config/config.default.js
      - /usr/local/smart-signature/ss-backend-config/apiaccesstoken.js:/usr/src/app/config/apiaccesstoken.js
      - /usr/local/smart-signature/ss-backend-config/wechat_config.js:/usr/src/app/config/wechat_config.js
    ports:
      - 7652:7001
    networks:
      overlay:

networks:
  overlay:
