version: "3.9"

services:

  mysql_local:
    image: mysql:5.7
    container_name: mysql_local
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=6Oot_p@sSw0Rd
      - MYSQL_DATABASE=ss
      - MYSQL_USER=ss_test
      - MYSQL_PASSWORD=p@sSw0Rd
    volumes:
      - .data/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin", "ping", "--user=root", "--password=${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis_local:
    image: redis:7
    container_name: redis_local
    restart: unless-stopped
    ports:
      - 6379:6379
    command: >
      --requirepass p@sSw0Rd
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch_local:
    image: elasticsearch:7.17.10
    container_name: elasticsearch_local
    restart: unless-stopped
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - .data/elasticsearch:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  ipfs_local:
    image: ipfs/kubo
    container_name: ipfs_local
    restart: unless-stopped
    ports:
      - 5001:5001
      - 8080:8080
    volumes:
      - .data/ipfs:/data/ipfs
    healthcheck:
      test: ["CMD-SHELL", "ipfs dag stat /ipfs/QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 5s

  ss_backend:
    restart: always
    container_name: ss_backend_local
    build:
      context: .
      dockerfile: ./Dockerfile
    command: yarn serve
    volumes:
      - ./config/config.local.js:/usr/src/app/config/config.local.js
      - ./config/apiaccesstoken.js:/usr/src/app/config/apiaccesstoken.js
      - ./config/wechat_config.js:/usr/src/app/config/wechat_config.js
      - ./posts-zip:/usr/src/app/posts-zip
    ports:
      - 7653:7001
    depends_on:
      - mysql_local
      - redis_local
      - elasticsearch_local
      - ipfs_local
    healthcheck:
      test: curl --fail http://localhost:7001 || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
